name: "Auto merge"
description: "Automatically merge pull requests with the 'Ready to merge' or 'Auto merge' label if they are not drafts."inputs:
inputs:
  token:
    description: "GitHub token with repo permissions"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        token: ${{ inputs.token }}

    - name: Rebase branch
      run: gh pr update-branch ${{ github.event.pull_request.number }} --rebase
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Enable auto merge or merge pull request
      run: gh pr merge ${{ github.event.pull_request.number }} --auto -s
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Approve pull request if it's from dependabot
      if: contains(github.event.pull_request.user.login, 'dependabot')
      run: gh pr review ${{ github.event.pull_request.number }} --approve
        shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
