name: update-node-version
description: "This workflow get the latest node js version and open a pull request to update that"

inputs:
  token:
    description: "GitHub token to create pull requests"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Get latest Node.js version
      id: get-latest-node
      shell: bash
      run: |
        LATEST_VERSION=$(curl -s https://nodejs.org/dist/index.json | jq -r '.[0].version' | sed 's/v//')
        echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT

    - name: Check if .nvmrc file is up to date
      id: check-nvmrc
      shell: bash
      run: |
        if [ ! -f .nvmrc ]; then
          echo ".nvmrc file not found, creating it with the latest version."
          echo "${{ steps.get-latest-node.outputs.LATEST_VERSION }}" > .nvmrc
          echo "UP_TO_DATE=false" >> $GITHUB_OUTPUT
        else
          CURRENT_VERSION=$(cat .nvmrc)
          if [ "$CURRENT_VERSION" = "${{ steps.get-latest-node.outputs.LATEST_VERSION }}" ]; then
            echo "UP_TO_DATE=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "UP_TO_DATE=false" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Update .nvmrc file
      if: steps.check-nvmrc.outputs.UP_TO_DATE == 'false'
      shell: bash
      run: |
        echo "${{ steps.get-latest-node.outputs.LATEST_VERSION }}" > .nvmrc
        git config user.name "edp5-service"
        git config user.email "edp5-service@users.noreply.github.com"
        git checkout -b update-node-version-to-${{ steps.get-latest-node.outputs.LATEST_VERSION }}
        git add .nvmrc
        git commit -m "bump: Update Node.js version to ${{ steps.get-latest-node.outputs.LATEST_VERSION }}"
        git push origin update-node-version-to-${{ steps.get-latest-node.outputs.LATEST_VERSION }}

    - name: Create Pull Request
      if: steps.check-nvmrc.outputs.UP_TO_DATE == 'false'
      shell: bash
      run: |
        gh pr create --title "bump: Update Node.js version to ${{ steps.get-latest-node.outputs.LATEST_VERSION }}" --body "This PR updates the Node.js version in the .nvmrc file to the latest version ${{ steps.get-latest-node.outputs.LATEST_VERSION }}."
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
