name: "release"
description: "Generate a changelog and release a repository with semantic-release"
inputs:
  token:
    description: "GitHub token with repo permissions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Copy the releaserc to workspace
      shell: bash
      run: cp ${{ github.action_path }}/.releaserc.json ${{ github.workspace }}/.releaserc.json

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version-file: .nvmrc

    - name: Release with semantic-release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        extra_plugins: |
          @semantic-release/exec
          @semantic-release/changelog
          @semantic-release/git
          conventional-changelog-conventionalcommits
