name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and setup node
        uses: edp5/edp5-actions/checkout-node@main
        with:
          file-version: .nvmrc
          installCommand: npm ci

      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout and setup node
        uses: edp5/edp5-actions/checkout-node@main
        with:
          file-version: .nvmrc
          installCommand: npm ci

      - name: Run tests
        run: npm test
